### ISSUE TITLE
Isolator does not seem to acknowledge --work_dir option in Mesos

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [emccode/mesos-module-dvdi#104]
When testing out mesos-module-dvdi in the context of DC/OS 1.7, a user reported this abort upon integrating the module and restarting the agent:

```
Jun 05 06:33:23 dcostest-gra1-slavepub01 mesos-slave[4942]: I0605 06:33:23.179944  4951 state.cpp:58] Recovering state from '/tmp/mesos'
Jun 05 06:33:23 dcostest-gra1-slavepub01 mesos-slave[4942]: ABORT: (/pkg/src/mesos/3rdparty/libprocess/3rdparty/stout/include/stout/result.hpp:114): Result::get() but state == NONE
Jun 05 06:33:23 dcostest-gra1-slavepub01 mesos-slave[4942]: *** Aborted at 1465108403 (unix time) try "date -d @1465108403" if you are using GNU date ***
```

It looks like the module did not acknowledge the `MESOS_WORK_DIR=/var/lib/mesos` default in DC/OS,  and attempted to read from a missing folder. This was confirmed by creating the folder with appropriate permissions, which un-blocked mesos-slave.

It's possible that this is the correct location for that path, in which case the module may want to create it if it doesn't exist.

**Comment by davidvonthenen** [comment]
Hi @jgarcia-mesosphere,

The working directory is independent of where the checkpointed data for the isolators mount tracking goes. Based on feedback from other people at Mesosphere, it was decided that the checkpoint data will reside in /var/run/mesos/isolators/mesos-module-dvdi. Please see this issue https://github.com/emccode/mesos-module-dvdi/issues/94 for more details.

This fix is currently not apart of the release you are using, but has already been committed to master. A release containing this fix is TBD. My guess is that when 1.0 has exited RC is when we will have a release with this fix.

**Comment by jgarcia-mesosphere** [comment]
Awesome thanks!
