### ISSUE TITLE
Support for Mesos 1.2.0 needed

### ISSUE THREAD

**Issue by cantbewong** [emccode/mesos-module-dvdi#128]
Mesos 1.2.0 was recently released and should be supported by the isolator

**Comment by chadleeshaw** [comment]
+1

**Comment by chadleeshaw** [comment]
Thanks for the merge!  Can we get a built shared object as well?

**Comment by davidvonthenen** [comment]
@utsysadmin Yep, I will try and cut a release this week. I am at ApacheCon right now so will be doing that along with taking care of my day to day stuff.

**Comment by davidvonthenen** [comment]
I am assuming this works since we havent gotten any feedback. Closing.
