### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by drcrallen** [emccode/mesos-module-dvdi#131]
Since https://github.com/codedellemc/mesos-module-libstorage also uses dvdcli, why would one be used vs the other?

**Comment by davidvonthenen** [comment]
libstorage has been re-absorbed into REX-Ray.

Also, as of mesos 1.0 or higher, native external volume support is available. Please take a look at:
https://github.com/codedellemc/mesos-module-dvdi/issues/132
