### ISSUE TITLE
Support for Mesos 1.3.0 needed

### ISSUE THREAD

**Issue by hhkbble** [emccode/mesos-module-dvdi#132]
Mesos 1.3.0 was recently released and should be supported by the isolator

**Comment by davidvonthenen** [comment]
@haoyixin I will take a look at it in the morning and hopefully cut a release. There have been other updates to different versions. Good to get a formal release out.

**Comment by davidvonthenen** [comment]
Official GA bits aren't available yet for download. In the mesos mailing list, they just had a vote on rc3. Will revisit when it GAs.

**Comment by hhkbble** [comment]
@dvonthenen thx for recent reply and 1.3.0 GA had released now ^_^

**Comment by Lax77** [comment]
Mesos 1.3.0 is been out for a while, is there a plan to release compatible isolator release? Unfortunately this is limiting us not to upgrade Mesos beyond version 1.2.0

**Comment by davidvonthenen** [comment]
@Lax77 @haoyixin Have you tried using the native external mount isolator that is baked into mesos? It is essentially a fork of this project that has been modified slightly to use proper mesos speak. 
Docs: https://mesosphere.github.io/marathon/docs/external-volumes.html

If you have, why do you prefer using our version of the isolator? Just trying to understand the use case(s).

**Comment by Lax77** [comment]
Thanks for the response @dvonthenen . No specific reason, I wasn't aware of the native mount isolator. I happened to use Rex-ray and somehow got referred to this project. 

Btw, in the link you given in do not find the link to native external mount isolator installation, only about the external volume configuration part which is assuming isolator is in place. Do you happened to have link where I can fetch the native isolator from? - Thanks

**Comment by davidvonthenen** [comment]
@lax77 its native to mesos meaning that it ships with mesos out of the box. nothing to download and install. You still need rexray to be installed and configured, but the isolator part is taken care of.

**Comment by Lax77** [comment]
Ok, Thanks @dvonthenen
