### ISSUE TITLE
refactor mount list file implementation to use a google protocol buffers implementation instead of picoJSON

### ISSUE THREAD

**Issue by cantbewong** [emccode/mesos-module-dvdi#19]
Google protocol buffer is the standard mechanism within Mesos for rendering and passing configuration and parameters. It is likely to better handle versioning and schema definition.

**Comment by clintkitson** [comment]
https://github.com/emccode/mesos-module-dvdi/commit/81fbbae1876521ec1c1a36bee43ba11c4a6b9dbe
