### ISSUE TITLE
Support pre-emptive mounts of an external storage volume as an option

### ISSUE THREAD

**Issue by cantbewong** [emccode/mesos-module-dvdi#23]
Some storage platforms, and some/most file systems prevent concurrent mounts of a volume from multiple users.

If a Mesos agent mount a volume and abnormally terminates, and the same or an alternate workload subsequently tries to mount the volume, without a dismount from the original location, the second mount can potentially fail. Some storage platforms have a mechanism for supporting a "pre-emptive mount" option which will force-ibly remove the first mount when the second mount is attempted. 

Resolution of this issue is dependent on resolution of a corresponding issue in the RexRay project. See: https://github.com/emccode/rexray/issues/30

**Comment by clintkitson** [comment]
Documentation update to show how to do it with REX-Ray 0.3.

**Comment by clintkitson** [comment]
https://github.com/clintonskitson/rexray/tree/feature/preemption

**Comment by cantbewong** [comment]
closed by merge of last PR
