### ISSUE TITLE
Support Mesos v0.28.0

### ISSUE THREAD

**Issue by cantbewong** [emccode/mesos-module-dvdi#42]

**Comment by gyliu513** [comment]
@cantbewong are you still planning to support 0.28? Or just merge this to mesos? Can you please show some of your idea here: https://docs.google.com/document/d/1uhi1lf1_sEmnl0HaqHUCsqPb9m9jOKbRlXYW1S-tZis/edit

**Comment by cantbewong** [comment]
yes, we will continue support until the merge, and probably after too if
anything needs to be done for users of Mesos version 0.23 -0.27

And I expect we will support 0.28

**Comment by gyliu513** [comment]
When will 0.28 support can be finished here?

**Comment by davidvonthenen** [comment]
@jay-lau the support for 0.28.0 will be added right after it is released. There are votes for the 0.28.0 RC going on right now.

**Comment by gyliu513** [comment]
@dvonthenen  does the code for mesos-module-dvdi is finished or not? Can you please share it? I was working on the FS for https://issues.apache.org/jira/browse/MESOS-4355 and want to make the external volume management to Mesos. A draft fs is here: https://docs.google.com/document/d/1uhi1lf1_sEmnl0HaqHUCsqPb9m9jOKbRlXYW1S-tZis/edit

**Comment by davidvonthenen** [comment]
@jay-lau I have not evaluated 0.28.0 yet so I dont know if there are code changes to be made. I usually dont start taking a look until the release is out in order to reduce spinning our tires.

**Comment by gyliu513** [comment]
@dvonthenen There are huge change in mesos containerizer and docker integration, the mesos containerizer will not depend on docker daemon to create containers. Please refer to https://issues.apache.org/jira/browse/MESOS-2840 for detail. I do hope you guys can work with me to update the document https://docs.google.com/document/d/1uhi1lf1_sEmnl0HaqHUCsqPb9m9jOKbRlXYW1S-tZis/edit# here for https://issues.apache.org/jira/browse/MESOS-4355

**Comment by cantbewong** [comment]
I don't think the mesos containerizer has a dependency on the docker daemon
now, so this would not be a change.

Could be I'm wrong, but you could test this theroy by disabling or removing
the docker daemon

**Comment by gyliu513** [comment]
Yes, the mesos will not depend on docker daemon now, but the problem is that the mesos containerizer will try to provision a rootfs for docker container with docker image.

**Comment by cantbewong** [comment]
is there a Mesos JIRA or design document for this change?

**Comment by gyliu513** [comment]
https://issues.apache.org/jira/browse/MESOS-2840

**Comment by pradeepchhetri** [comment]
@cantbewong As far as i got by reading the design documentation and docs in mesos repository, there are various things related to docker which are still not added in mesos containerizer and definitely its not production ready (experimental support only). 
For example: currently it doesn't support BRIDGE networking mode (https://github.com/apache/mesos/blob/master/docs/container-image.md#docker-support-and-current-limitations). 

Can we build the module for 0.28.0 (0.28.1 is coming soon too with some bug fixes) please ?

**Comment by gyliu513** [comment]
The network support will be coming soom here with CNI support https://issues.apache.org/jira/browse/MESOS-4641

**Comment by cantbewong** [comment]
published in v0.4.2
