### ISSUE TITLE
Single Code base to Support Versions going back to 0.23.0

### ISSUE THREAD

**Issue by davidvonthenen** [emccode/mesos-module-dvdi#44]
Either via a series of ifdefs or some type of abstraction interface, support versions of mesos going back to 0.23.0

**Comment by davidvonthenen** [comment]
Coding I believe is complete.... just need to verify and then integrate with CI

**Comment by clintkitson** [comment]
Where's the link to the commit?

**Comment by davidvonthenen** [comment]
I havent tested yet which is why it hasnt been committed yet. The testing on multiple versions of mesos and the integration with CI is going to be the tricky and time consuming part. I should have the PR by no later than the end of the week.

**Comment by clintkitson** [comment]
But the latest commit you are working on should be stashed in your forked repo.

**Comment by davidvonthenen** [comment]
PR merged
https://github.com/emccode/mesos-module-dvdi/pull/49
