### ISSUE TITLE
Is it support docker container in this module?

### ISSUE THREAD

**Issue by heww** [emccode/mesos-module-dvdi#51]
Hi, I install this module in mesos 0.25.0 with rexray 0.3.0 on OpenStack.

I test that  example in README, then cinder volume is created.

But, I test with docker container in mesos , cinder volume is not created at all. Here is my json file deploy by Marathon 0.13.0. And I want to know that this module whether support docker container at this moment.

``` json
{
    "id": "demo",
    "mem": 512,
    "cpus": 0.5,
    "instances": 1,
    "container": {
        "type": "DOCKER",
        "docker": {
            "network": "BRIDGE",
            "image": "nginx:1.9.6",
            "portMappings": [{
                "containerPort": 80,
                "protocol": "tcp"
            }]
        },
        "volumes": [{
            "containerPath": "/usr/share/nginx/html",
            "hostPath": "/var/lib/rexray/volumes/demo",
            "mode": "RO"
        }]
    },
    "env": {
        "DVDI_VOLUME_NAME": "demo",
        "DVDI_VOLUME_DRIVER": "rexray",
        "DVDI_VOLUME_OPTS": "size=5,iops=150,newfstype=xfs,overwritefs=true",
        "DVDI_VOLUME_CONTAINERPATH": "/var/lib/rexray/volumes/demo"
    }
}
```

**Comment by clintkitson** [comment]
Hello!

The Docker containerizer does not invoke the dvdi module.  Since Docker has
volume functionality natively, they are different parameters that are set.

See following blog post.

http://blog.emccode.com/2015/08/28/run-your-stateful-apps-with-mesos-and-docker/

**Comment by heww** [comment]
I test following the blog, it's ok, thanks!
