### ISSUE TITLE
resolve container isolation behavior for special use cases

### ISSUE THREAD

**Issue by cantbewong** [emccode/mesos-module-dvdi#53]
This describes desired behavior:
1. What happens if the container path is not specified or is empty?
no isolation, and mount is visible to all tasks on agent node
1. What happens is container path is relative (no / prefix)?
   failure returned from prepare()
2. Currently the isolator allow multiple tasks to ask for a mount of the same volume. When this happens, all tasks share the volume.
   What happens if MULTIPLE  tasks ask for the same volume AND also specify a container path to ask for isolation?
   First task succeeds, any subsequent task asking for isolation gets failure on prepare(), since specifying a container path implies an expectation of isolation.
3. When a container path is specified, and does not exist at prepare() time on the agent node, should the container path directory be automatically created on the agent node? 
   Or should this result in a failure?
   If the container path is auto-created, should it be removed when unmount occurs? 
   If it should be removed, what happens if a second task arrives bringing use count of container path >1? 
   If auto-created container paths are not removed, will proliferation of these over time cause problems such as inode exhaustion?
   Answer: 
   Auto-create only if container path is under /tmp. Never remove. (although OS /tmp processing may remove on reboot.)  
   If the containerpath is not under /tmp, and does not exist, fail on prepare()
4. When a mount is isolated with a container path, should the ownership and permissions be copied from container path to mount path?
   Answer: always copy ownership and permissions from containerpath to mountpoint

Implement these behaviors

**Comment by clintkitson** [comment]
If a container path is specified for the same volume from multiple tasks
then the assumption is that the containers should each have access to that
volume in the specified container path.

The isolation is relative to the main container file system.  Additive
volumes should be able to be shared between containers.

**Comment by clintkitson** [comment]
Just thought of something.  In docker land the sharing of a volume
typically possible because you can specify the volume to a specific docker
runtime.  Also there is an explicit flag to allow it as well by specifying
volumesfrom another container.

Since it's not possible today in Mesos to target a specific agent based on
where volumes are currently mounted then this would be invalid.

It could be an interesting addition in the future however.  So I take back
what I said.

**Comment by cantbewong** [comment]
closed by last PR
