### ISSUE TITLE
question: what is the volume life cycle

### ISSUE THREAD

**Issue by osallou** [emccode/mesos-module-dvdi#62]
Docker volume plugin has Create/Mount/Unmount/Delete operations.

Will all those methods be called on container startup/destroy ? At which step of the mesos container life cycle?

Thanks

**Comment by davidvonthenen** [comment]
Hi,

When the a request for a volume is made, the following will take place:
1) if the volume doesnt exist by name, the volume will be created with the give attributes and then mounted.
2) if the volume already exists, all the assoicated "create" parameters will be ignored and the volume will be mounted.

When the mesos task is destroyed, the volume will simply be unmounted. This facilitates reuse of the volume for specific use cases. For example, if the slave node fails, the task can be brought up another node with its data intact.

Delete is never called. Clean up can be done out of band or on the create, you can overwrite the existing filesystem effectively wiping the data.

**Comment by davidvonthenen** [comment]
Hi osallou,

Does this sufficient answer your questions? May I close this issue out?

Thanks!

**Comment by osallou** [comment]
You can close the issue, thanks

Le dim. 31 janv. 2016 18:10, David vonThenen notifications@github.com a
écrit :

**Comment by davidvonthenen** [comment]
No problem. If you have any other questions, you can stop by our codecommunity.slack.com channel and join #mesos.
