### ISSUE TITLE
Build for mesos v0.27.0

### ISSUE THREAD

**Issue by pradeepchhetri** [emccode/mesos-module-dvdi#70]
It will be nice if we can add support for building dvdi module with mesos v0.27.0.

**Comment by davidvonthenen** [comment]
Yep, we are working on it. We are waiting for the official 27 binaries for qualification.

Already have an issue open for 0.27.0, you can find it here: https://github.com/emccode/mesos-module-dvdi/issues/43

**Comment by cantbewong** [comment]
closing as a duplicate of issue 43
