### ISSUE TITLE
make fails to download subversion

### ISSUE THREAD

**Issue by DarinJ** [emccode/mesos-module-dvdi#74]
Bumping SVN_VER := 1.9.2 to SVN_VER := 1.9.3 solves the issue.

**Comment by cantbewong** [comment]
Investigating, thanks

**Comment by cantbewong** [comment]
Yes, looks like apache mirror no longer sources the 1.9.2 version
I will fix this

**Comment by davidvonthenen** [comment]
This issue should be fixed now. Builds against 1.9.3.
