### ISSUE TITLE
Make this as part of Mesos

### ISSUE THREAD

**Issue by gyliu513** [emccode/mesos-module-dvdi#80]
@cantbewong I'm planning to work on https://issues.apache.org/jira/browse/MESOS-4355 , this is exactly what you are doing now for this project, do you have any comments we make this upstream to mesos?

**Comment by cantbewong** [comment]
I just added a comment to the jira that you should look at.

If you don't understand it, I would be happy to discuss.

FYI: I am located in the US Pacific timezone (Los Angeles)

I don't know where you are located, but I will be traveling to Mesosphere
in San Francisco next Wednesday if you are located there, perhaps we can
meet.

**Comment by gyliu513** [comment]
Thanks  @cantbewong , I was located in China and planning to finish the design of MESOS-4355 recently, it would be great if you can work as a co-author of this project. If we can put this as an official isolator in Mesos, then it will be much easier to maintain this. ;-)

**Comment by cantbewong** [comment]
yes, I would like to work on the project

**Comment by gyliu513** [comment]
Can you please share your email address with me so that we can communicate more via email? Thanks.
