### ISSUE TITLE
[Question] Why does the dvdi need to call "unmount" when isolator "cleanup"

### ISSUE THREAD

**Issue by gyliu513** [emccode/mesos-module-dvdi#90]
Here come a question is `Why does the dvdi need to call "unmount" when isolator "cleanup"`? I did not see much impact if we do not do `unmount` when isolator `cleanup` or `recover`, the only issue is that there will be some garbage mount info in`/proc/mounts`, any comments?

**Comment by clintkitson** [comment]
Leaving this one for @cantbewong

**Comment by gyliu513** [comment]
@cantbewong any comments on this? Thanks.

**Comment by cantbewong** [comment]
For external mounts, you want to unmount so that the task can be rescheduled to another agent node.

Some storage platforms do suppport pre-emptive mount, but some do not. Even when a pre-emptive mount is supported, it takes more time if the external volume is mounted elsewhere

**Comment by cantbewong** [comment]
Please close this issue if I answered your question

**Comment by gyliu513** [comment]
@cantbewong can you please show more detail for `pre-emptive mount`? Does there an example for this?

**Comment by gyliu513** [comment]
Also can you please show more detail for `For external mounts, you want to unmount so that the task can be rescheduled to another agent node.` ? Which framework support task reschedule? Does the reschedule means that if the task failed, find another agent host to re-run the task again? Thanks @cantbewong

**Comment by cantbewong** [comment]
For detail on pre-emptive mount please see the section titled Pre-emptive Volume Mount right on the readme.md file for this repo.

Marathon supports rescheduling to another agent node and this is what we test with. There is no reason that this can't be done by other Frameworks as well. One use case is a scenario where an agent node crashes or is permanently retired. Another is a batch workloads that can flexibly be run on any agent node offering sufficient resources.

**Comment by gyliu513** [comment]
@cantbewong thanks.
