### ISSUE TITLE
[Question] How can I check the bind mount info via namespace after "dvdcli mount"

### ISSUE THREAD

**Issue by gyliu513** [emccode/mesos-module-dvdi#91]
Does there are any files can enable me do the check?

The reason is that when I was doing the project of https://issues.apache.org/jira/browse/MESOS-4355 , the shepherd has a question: He think that we do not need do `dvdcli umount` when `cleanup` or `recover`, we want to make sure there is no impact if we did not call `unmount` when `cleanup` or `recover`.

Another point from shepherd is that we run the `dvdcli mount` in container's namespace, so we do not need to `unmount` when clean up as the mount point will be managed by the container, once container goes away, the mount point also goes away. So I was verifying those issues and want to get some help from you guys. Thanks.

**Comment by clintkitson** [comment]
Let me leave this one for @cantbeong to address.

**Comment by gyliu513** [comment]
I was using convoy nfs driver first and the driver will not generate mount point, after switching to devicemaper, it works well and I can check the mount point via /proc/mounts.
