### ISSUE TITLE
Checkpointed data should not be put in agent's metadata workdir by default.

### ISSUE THREAD

**Issue by jieyu** [emccode/mesos-module-dvdi#94]
We should avoid that since that directory is owned by the Mesos agent. Mesos does not expect an isolator to put checkpointed data there. We should put it under /var/run/mesos/isolators/<isolator-name>.

The directory in which the checkpointed data is put should be cleaned up on reboot. Otherwise, the isolator will try to recovery the checkpointed data after the reboot, thinking that mounts are still there. Therefore, putting checkpointed data under /var/run is recommended as it'll get cleaned up on reboot.

**Comment by cantbewong** [comment]
OK, this change makes sense and is feasible for next release

**Comment by davidvonthenen** [comment]
Currently the checkpoint info is stored at:
/tmp/mesos/meta/dvdimounts.pb

We will be moving to:
/var/run/mesos/isolators/mesos-module-dvdi/dvdimounts.pb

Unless anyone has any objections.

**Comment by davidvonthenen** [comment]
PR https://github.com/emccode/mesos-module-dvdi/pull/102 pending

**Comment by davidvonthenen** [comment]
Has been merged. If there any issues, please let us know.
