### ISSUE TITLE
Support explicitCreate flag from dvdcli

### ISSUE THREAD

**Issue by clintkitson** [emccode/mesos-module-dvdi#97]
@cantbewong @dvonthenen 

https://github.com/emccode/dvdcli/pull/20

There is a 0.2.0 release of dvdcli coming out shortly. I reviewed the current isolator code, and I believe there should not be any net effect as is.

There was a change in the `dvdcli` to update it against the Docker 1.11.0 volume API. The biggest change is that we now have the ability to check whether a volume exists prior to any operation. Prior, we would implicitly create volumes no matter what when commands were ran with dvdcli.

There is a new flag `--explicitCreate=true` that need to be set to enable this new functionality. Without it, implicit will still work for mesos-module-dvdi as before and new volumes can be specified with the task. Let's figure out how to get this into the next release of the module where a parameter can be set for the agent that defined whether explicitCreate is used or not.

**Comment by davidvonthenen** [comment]
Will have a PR today for this.

**Comment by davidvonthenen** [comment]
PR submitted.

**Comment by davidvonthenen** [comment]
Merged.
