### ISSUE TITLE
incorrect path to dvdcli on CoreOS

### ISSUE THREAD

**Issue by mitel** [emccode/mesos-module-dvdi#99]
Hello, the library will not work on CoreOS (eg: DC/OS) due to the following:

isolator/isolator/docker_volume_driver_isolator.hpp:
static constexpr char DVDCLI_MOUNT_CMD[]          = "/usr/bin/dvdcli mount";
static constexpr char DVDCLI_UNMOUNT_CMD[]        = "/usr/bin/dvdcli unmount";

whereas dvdcli will install in /opt/bin on CoreOS:
if [ -n "$IS_COREOS" ]; then
  BIN_DIR=/opt/bin
  BIN_FILE=$BIN_DIR/$BIN_NAME

**Comment by davidvonthenen** [comment]
There is a PR https://github.com/emccode/mesos-module-dvdi/pull/100 ending that should help address this in a generic fashion

**Comment by davidvonthenen** [comment]
The PR mentioned above has been merged. We can now specify which DVDCLI to use by fully qualified path per task. If this doesn't meet you requirements, we can revisit the issue.
